# config.toml

# Hostname / IP
#
# Default: "localhost"
#
host = "127.0.0.1"

# Port
#
# Default: 8282
#
port = 8282

# Database Type
# Set database type to use. Supported: sqlite, postgres
# If not defined, sqlite will be used by default.
# Make sure postgres is installed and running before using it.
#
# Optional
#
#DatabaseType = "sqlite"

# Postgres Host
# Set postgres host to use.
#
# Optional
#
#PostgresHost = "localhost"

# Postgres Port
# Set postgres port to use.
#
# Optional
#
#PostgresPort = "5434"

# Postgres Database
# Set postgres database to use.
# If not defined, It will use the default database. (postgres)
#
# Optional
#
#PostgresDatabase = "postgres"

# Postgres User
# Set postgres user to use.
#
#PostgresUser = "SyncYomi"

# Postgres Pass
# Set postgres password to use.
#
#
#PostgresPass = "SyncYomi"

# Base url
# Set custom baseUrl eg /tachiyomi/ to serve in subdirectory.
# Not needed for subdomain, or by accessing with the :port directly.
#
# Optional
#
#baseUrl = "/SyncYomi/"

# tachiyomi-sync-server logs file
# If not defined, logs to stdout make sure it's forward slash otherwise it won't work
#
# Optional
#
#logPath = "log/SyncYomi.log"

# Log level
#
# Default: "DEBUG"
#
# Options: "ERROR", "DEBUG", "INFO", "WARN", "TRACE"
#
logLevel = "DEBUG"

# Log Max Size
#
# Default: 50
#
# Max log size in megabytes
#
#logMaxSize = 50

# Log Max Backups
#
# Default: 3
#
# Max amount of old log files
#
#logMaxBackups = 3

# Check for updates
#
checkForUpdates = true

# Session secret
#
sessionSecret = "37335a8067c2fb35a3cbe13386a62243"
